# Generated by Django 5.1.3 on 2024-12-05 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='test_name',
            new_name='last_name',
        ),
    ]
