# Generated by Django 5.1.3 on 2024-12-05 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_rename_test_name_student_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stdent_number',
            new_name='student_number',
        ),
    ]
